/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import AccesoADatos.ProveedorData;
import Entidades.Proveedor;
import static Vistas.mainMenu.Escritorio;
import static Vistas.mainMenu.mensaje;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ariel
 */
public class AdminProveedoresIF extends javax.swing.JInternalFrame {

    private ProveedorData provD;
    private DefaultTableModel modelo = new DefaultTableModel();
    List<Proveedor> lista = new ArrayList<>(); 
    public AdminProveedoresIF(ProveedorData provD) {
        this.provD = provD;
        initComponents();
        armarCabecera();
        ActivosRB.setSelected(true);
        listar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Grupo = new javax.swing.ButtonGroup();
        AgregarB = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        DomicilioT = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        EmailT = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TelefonoT = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        ProveedorTabla = new javax.swing.JTable();
        ModificarB = new javax.swing.JButton();
        EstadoB = new javax.swing.JButton();
        RazonST = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        ActivosRB = new javax.swing.JRadioButton();
        InactivosRB = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Administrar Proveedores");
        setToolTipText("");
        setMaximumSize(new java.awt.Dimension(1008, 605));
        setMinimumSize(new java.awt.Dimension(1008, 605));

        AgregarB.setText("Agregar nuevo Proveedor");
        AgregarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarBActionPerformed(evt);
            }
        });

        jLabel1.setText("Razon Social");

        jLabel2.setText("Domicilio");

        jLabel3.setText("Email");

        jLabel4.setText("Telefono");

        ProveedorTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(ProveedorTabla);

        ModificarB.setText("Modificar Proveedor");
        ModificarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarBActionPerformed(evt);
            }
        });

        EstadoB.setText("Modificar Estado");
        EstadoB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EstadoBActionPerformed(evt);
            }
        });

        jLabel7.setText("Agregar nuevo Proveedor");

        jLabel8.setText("Gestionar proveedores existentes");

        Grupo.add(ActivosRB);
        ActivosRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActivosRBActionPerformed(evt);
            }
        });

        Grupo.add(InactivosRB);
        InactivosRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InactivosRBActionPerformed(evt);
            }
        });

        jLabel5.setText("Mostrar :");

        jLabel6.setText("Inactivos");

        jLabel9.setText("Activos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(168, 168, 168))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(DomicilioT, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                            .addComponent(EmailT)
                            .addComponent(TelefonoT)
                            .addComponent(RazonST)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(AgregarB)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 125, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ModificarB)
                        .addGap(164, 164, 164)
                        .addComponent(EstadoB))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(64, 64, 64))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(33, 33, 33)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(InactivosRB)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addGap(25, 25, 25)
                .addComponent(ActivosRB)
                .addGap(231, 231, 231))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(RazonST, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(DomicilioT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(EmailT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(TelefonoT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(AgregarB))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel8)
                        .addGap(37, 37, 37)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EstadoB)
                    .addComponent(ModificarB))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ActivosRB)
                    .addComponent(jLabel9)
                    .addComponent(InactivosRB)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(jLabel5)))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AgregarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarBActionPerformed
        // Agregar proveedor
        try{
            String razonSoc = RazonST.getText();
            String domicilio = DomicilioT.getText();
            String email = EmailT.getText();
            String telefono = TelefonoT.getText();
            
            Proveedor prov = new Proveedor(razonSoc, domicilio, email, telefono, true);
            
            provD.agregarProveedor(prov);
            
            RazonST.setText("");
            DomicilioT.setText("");
            EmailT.setText("");
            TelefonoT.setText("");
            
            listar();
        }catch(NullPointerException ex){
            mensaje("Hay campos vacíos o valores mal ingresados, revisar el formulario");
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_AgregarBActionPerformed

    private void ModificarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarBActionPerformed
        // Boton modificar proveedor
         try{   
            int fila = ProveedorTabla.getSelectedRow();
            
            int id = (int) ProveedorTabla.getValueAt(fila, 0);
            Proveedor modificar = new Proveedor();
            modificar = lista.get(fila);
             System.out.println(modificar);
            ModificarProveedorIF mpif = new ModificarProveedorIF(provD, modificar);
            mpif.setVisible(true);
            Escritorio.add(mpif);
            Escritorio.moveToFront(mpif);
         }catch(ArrayIndexOutOfBoundsException ex){
            mensaje("Debe seleccionar un producto de la tabla.");
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_ModificarBActionPerformed

    private void ActivosRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActivosRBActionPerformed
        // Boton activo
        listar();
    }//GEN-LAST:event_ActivosRBActionPerformed

    private void InactivosRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InactivosRBActionPerformed
        // Boton inactivos
        listar();
    }//GEN-LAST:event_InactivosRBActionPerformed

    private void EstadoBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EstadoBActionPerformed
        // Boton para dar de baja
        try{
            int fila = ProveedorTabla.getSelectedRow();

            int id = (int) ProveedorTabla.getValueAt(fila, 0);
            if(ActivosRB.isSelected()){
                provD.altaBajaProveedores(0, id);
            }else{
                provD.altaBajaProveedores(1, id);
            }
            
            listar();
        }catch(ArrayIndexOutOfBoundsException ex){
            mensaje("Debe seleccionar un producto de la tabla.");
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_EstadoBActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton ActivosRB;
    private javax.swing.JButton AgregarB;
    private javax.swing.JTextField DomicilioT;
    private javax.swing.JTextField EmailT;
    private javax.swing.JButton EstadoB;
    private javax.swing.ButtonGroup Grupo;
    private javax.swing.JRadioButton InactivosRB;
    private javax.swing.JButton ModificarB;
    private javax.swing.JTable ProveedorTabla;
    private javax.swing.JTextField RazonST;
    private javax.swing.JTextField TelefonoT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private void armarCabecera(){
        modelo.addColumn("ID");
        modelo.addColumn("Razón Social");
        modelo.addColumn("Dirección");
        modelo.addColumn("E-Mail");
        modelo.addColumn("Teléfono");
        ProveedorTabla.setModel(modelo);
    }
    
    public void listar(){
        borrarFilas();
        if (ActivosRB.isSelected()) {
            lista = provD.listarProveedores(1);
        } else if(InactivosRB.isSelected()){
             lista = provD.listarProveedores(0);
        }
        
       for (Proveedor prov : lista) {
            modelo.addRow(new Object[]{prov.getIdProveedor(),prov.getRazonSocial(),prov.getDomicilio(),prov.getEmail(),prov.getTelefono()});
        }
    }
    
    public void borrarFilas(){
        int f = ProveedorTabla.getRowCount() - 1;
        for (; f >= 0; f--) {
            modelo.removeRow(f);
        }
    }
}
