/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import AccesoADatos.ComprasData;
import AccesoADatos.DetalleData;
import AccesoADatos.ProductosData;
import AccesoADatos.ProveedorData;
import static Vistas.mainMenu.Escritorio;

public class HistorialCompraIF extends javax.swing.JInternalFrame {

    private ComprasData compD;
    private ProveedorData provD;
    private ProductosData prodD;
    private DetalleData detaD;
    /**
     * Creates new form HistorialCompraIF
     */
    public HistorialCompraIF(ComprasData compD, ProductosData prodD, ProveedorData provD, DetalleData detaD) {
        this.compD = compD;
        this.prodD = prodD;
        this.provD = provD;
        this.detaD = detaD;
        initComponents();
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comprasRealizadaB = new javax.swing.JButton();
        ProveedorB = new javax.swing.JButton();
        StockB = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        FondoHisc = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Historial de Compras");
        setPreferredSize(new java.awt.Dimension(335, 616));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        comprasRealizadaB.setBackground(new java.awt.Color(204, 204, 255));
        comprasRealizadaB.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        comprasRealizadaB.setForeground(new java.awt.Color(0, 0, 102));
        comprasRealizadaB.setText("Compras Realizadas");
        comprasRealizadaB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comprasRealizadaBActionPerformed(evt);
            }
        });
        getContentPane().add(comprasRealizadaB, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, -1, 40));

        ProveedorB.setBackground(new java.awt.Color(204, 204, 255));
        ProveedorB.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ProveedorB.setForeground(new java.awt.Color(0, 0, 102));
        ProveedorB.setText("Proveedores");
        ProveedorB.setPreferredSize(new java.awt.Dimension(157, 25));
        ProveedorB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProveedorBActionPerformed(evt);
            }
        });
        getContentPane().add(ProveedorB, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 130, 40));

        StockB.setBackground(new java.awt.Color(204, 204, 255));
        StockB.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        StockB.setForeground(new java.awt.Color(0, 0, 102));
        StockB.setText("Consultas Stock");
        StockB.setPreferredSize(new java.awt.Dimension(157, 25));
        StockB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StockBActionPerformed(evt);
            }
        });
        getContentPane().add(StockB, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 520, 140, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-supplier-100.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-buy-100.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-list-100.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 420, -1, -1));

        FondoHisc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FONDO3.jpg"))); // NOI18N
        getContentPane().add(FondoHisc, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ProveedorBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProveedorBActionPerformed

        ProveedoresIF mostrar = new ProveedoresIF(provD, prodD, compD);
        mostrar.setVisible(true);
        Escritorio.add(mostrar);
        Escritorio.moveToFront(mostrar);
       
    }//GEN-LAST:event_ProveedorBActionPerformed

    private void comprasRealizadaBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comprasRealizadaBActionPerformed

        ComprasRealizadasIF mostrar = new ComprasRealizadasIF(compD, detaD, prodD);
        mostrar.setVisible(true);
        Escritorio.add(mostrar);
        Escritorio.moveToFront(mostrar);
    }//GEN-LAST:event_comprasRealizadaBActionPerformed

    private void StockBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StockBActionPerformed
 
        ConsultaStockIF mostrar = new ConsultaStockIF(prodD);
        mostrar.setVisible(true);
        Escritorio.add(mostrar);
        Escritorio.moveToFront(mostrar);
    }//GEN-LAST:event_StockBActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FondoHisc;
    private javax.swing.JButton ProveedorB;
    private javax.swing.JButton StockB;
    private javax.swing.JButton comprasRealizadaB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
