/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import AccesoADatos.ComprasData;
import AccesoADatos.DetalleData;
import AccesoADatos.ProductosData;
import AccesoADatos.ProveedorData;
import Entidades.Productos;
import java.awt.Color;
import java.net.URL;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JDesktopPane;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.UIManager;

/**
 *
 * @author ariel
 */
public class mainMenu extends javax.swing.JFrame {
    
    private ProductosData prodD;
    private ProveedorData provD;
    private ComprasData compD;
    private DetalleData detaD;

    public mainMenu() {
        this.prodD = new ProductosData();
        this.provD = new ProveedorData();
        this.compD = new ComprasData();
        this.detaD = new DetalleData();
        initComponents();
//      setIconImage(new ImageIcon(getClass().getResource("src/Imagenes/icono-tuvi.png")).getImage());
         URL iconURL = mainMenu.class.getResource("/Imagenes/icons8-store-64.png");
            ImageIcon icon = new ImageIcon(iconURL);
            setIconImage(icon.getImage());
        this.setLocationRelativeTo(null);
        setResizable(false);
//        alertaStockBajo();

        //loggin();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Escritorio = new javax.swing.JDesktopPane();
        logito5 = new javax.swing.JLabel();
        logito3 = new javax.swing.JLabel();
        logito2 = new javax.swing.JLabel();
        logito4 = new javax.swing.JLabel();
        logito1 = new javax.swing.JLabel();
        logito6P = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ProductosB = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        ProveedoresB = new javax.swing.JButton();
        SolicitarB = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        HistorialB = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        VentasB = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        FondoFrame = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 102, 102));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Escritorio.setBackground(new java.awt.Color(0, 102, 102));
        Escritorio.setMaximumSize(new java.awt.Dimension(1010, 610));
        Escritorio.setMinimumSize(new java.awt.Dimension(1010, 610));

        logito5.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        logito5.setForeground(new java.awt.Color(255, 255, 255));
        logito5.setText("Bienvenidos a ComprasLocas");

        logito3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-laptop-100.png"))); // NOI18N

        logito2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-tv-100.png"))); // NOI18N

        logito4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-air-conditioner-100.png"))); // NOI18N

        logito1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-refrigerator-100.png"))); // NOI18N

        logito6P.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout logito6PLayout = new javax.swing.GroupLayout(logito6P);
        logito6P.setLayout(logito6PLayout);
        logito6PLayout.setHorizontalGroup(
            logito6PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1010, Short.MAX_VALUE)
        );
        logito6PLayout.setVerticalGroup(
            logito6PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 610, Short.MAX_VALUE)
        );

        Escritorio.setLayer(logito5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Escritorio.setLayer(logito3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Escritorio.setLayer(logito2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Escritorio.setLayer(logito4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Escritorio.setLayer(logito1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Escritorio.setLayer(logito6P, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout EscritorioLayout = new javax.swing.GroupLayout(Escritorio);
        Escritorio.setLayout(EscritorioLayout);
        EscritorioLayout.setHorizontalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EscritorioLayout.createSequentialGroup()
                .addGap(208, 208, 208)
                .addComponent(logito5, javax.swing.GroupLayout.PREFERRED_SIZE, 627, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(EscritorioLayout.createSequentialGroup()
                .addGap(462, 462, 462)
                .addComponent(logito2))
            .addGroup(EscritorioLayout.createSequentialGroup()
                .addGap(653, 653, 653)
                .addComponent(logito4))
            .addGroup(EscritorioLayout.createSequentialGroup()
                .addGap(262, 262, 262)
                .addComponent(logito1))
            .addGroup(EscritorioLayout.createSequentialGroup()
                .addGap(462, 462, 462)
                .addComponent(logito3))
            .addComponent(logito6P, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        EscritorioLayout.setVerticalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EscritorioLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(logito5)
                .addGap(348, 348, 348)
                .addComponent(logito2))
            .addGroup(EscritorioLayout.createSequentialGroup()
                .addGap(293, 293, 293)
                .addComponent(logito4))
            .addGroup(EscritorioLayout.createSequentialGroup()
                .addGap(293, 293, 293)
                .addComponent(logito1))
            .addGroup(EscritorioLayout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addComponent(logito3))
            .addComponent(logito6P, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        getContentPane().add(Escritorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 1010, 610));
        Escritorio.getAccessibleContext().setAccessibleName("");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-products-64.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, -1, -1));

        ProductosB.setBackground(new java.awt.Color(204, 204, 255));
        ProductosB.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ProductosB.setForeground(new java.awt.Color(0, 0, 102));
        ProductosB.setText("Productos");
        ProductosB.setBorder(null);
        ProductosB.setMaximumSize(new java.awt.Dimension(100, 100));
        ProductosB.setMinimumSize(new java.awt.Dimension(100, 100));
        ProductosB.setPreferredSize(new java.awt.Dimension(100, 100));
        ProductosB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductosBActionPerformed(evt);
            }
        });
        getContentPane().add(ProductosB, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 120, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-supplier-64.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));

        ProveedoresB.setBackground(new java.awt.Color(204, 204, 255));
        ProveedoresB.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ProveedoresB.setForeground(new java.awt.Color(0, 0, 102));
        ProveedoresB.setText("Gestionar Proveedores");
        ProveedoresB.setBorder(null);
        ProveedoresB.setMaximumSize(new java.awt.Dimension(100, 100));
        ProveedoresB.setMinimumSize(new java.awt.Dimension(100, 100));
        ProveedoresB.setPreferredSize(new java.awt.Dimension(100, 100));
        ProveedoresB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProveedoresBActionPerformed(evt);
            }
        });
        getContentPane().add(ProveedoresB, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 150, 30));

        SolicitarB.setBackground(new java.awt.Color(204, 204, 255));
        SolicitarB.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        SolicitarB.setForeground(new java.awt.Color(0, 0, 102));
        SolicitarB.setText("Solicitar Productos");
        SolicitarB.setBorder(null);
        SolicitarB.setMaximumSize(new java.awt.Dimension(100, 100));
        SolicitarB.setMinimumSize(new java.awt.Dimension(100, 100));
        SolicitarB.setPreferredSize(new java.awt.Dimension(100, 100));
        SolicitarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SolicitarBActionPerformed(evt);
            }
        });
        getContentPane().add(SolicitarB, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 140, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-buy-64.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 70, -1));

        HistorialB.setBackground(new java.awt.Color(204, 204, 255));
        HistorialB.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        HistorialB.setForeground(new java.awt.Color(0, 0, 102));
        HistorialB.setText("Historial de Compras");
        HistorialB.setBorder(null);
        HistorialB.setMaximumSize(new java.awt.Dimension(100, 100));
        HistorialB.setMinimumSize(new java.awt.Dimension(100, 100));
        HistorialB.setPreferredSize(new java.awt.Dimension(100, 100));
        HistorialB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HistorialBActionPerformed(evt);
            }
        });
        getContentPane().add(HistorialB, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 140, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-list-64.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 70, -1));

        VentasB.setBackground(new java.awt.Color(204, 204, 255));
        VentasB.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        VentasB.setForeground(new java.awt.Color(0, 0, 102));
        VentasB.setText("Ventas");
        VentasB.setBorder(null);
        VentasB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VentasBActionPerformed(evt);
            }
        });
        getContentPane().add(VentasB, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 570, 140, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-add-shopping-cart-64.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 500, -1, -1));

        FondoFrame.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoAzulaesDefinicion.png"))); // NOI18N
        getContentPane().add(FondoFrame, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ProductosBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductosBActionPerformed
        Escritorio.removeAll();
        Escritorio.repaint();
        ProductoIF mostrar = new ProductoIF(prodD);
        mostrar.setVisible(true);
        Escritorio.add(mostrar);
        Escritorio.moveToFront(mostrar);
        logito();
        Escritorio.add(logito6P);
        alertaStockBajo();
        
    }//GEN-LAST:event_ProductosBActionPerformed

    private void ProveedoresBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProveedoresBActionPerformed
        Escritorio.removeAll();
        Escritorio.repaint();
        AdminProveedoresIF mostrar = new AdminProveedoresIF(provD);
        mostrar.setVisible(true);
        Escritorio.add(mostrar);
        Escritorio.moveToFront(mostrar);
        logito();
        Escritorio.add(logito6P);
        alertaStockBajo();
       
    }//GEN-LAST:event_ProveedoresBActionPerformed

    private void SolicitarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SolicitarBActionPerformed
        Escritorio.removeAll();
        Escritorio.repaint();
        SolicitarProductoIF mostrar = new SolicitarProductoIF(compD, prodD, provD, detaD);
        mostrar.setVisible(true);
        Escritorio.add(mostrar);
        Escritorio.moveToFront(mostrar);
        logito();
        Escritorio.add(logito6P);
       
    }//GEN-LAST:event_SolicitarBActionPerformed

    private void HistorialBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HistorialBActionPerformed
        Escritorio.removeAll();
        Escritorio.repaint();
        HistorialCompraIF mostrar = new HistorialCompraIF(compD, prodD, provD, detaD);
        mostrar.setVisible(true);
        Escritorio.add(mostrar);
        Escritorio.moveToFront(mostrar);
        logito();
        Escritorio.add(logito6P);
        
    }//GEN-LAST:event_HistorialBActionPerformed

    private void VentasBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VentasBActionPerformed
        // Boton de ventas
        Escritorio.removeAll();
        Escritorio.repaint();
        VentasIF mostrar = new VentasIF(prodD);
        mostrar.setVisible(true);
        Escritorio.add(mostrar);
        Escritorio.moveToFront(mostrar);
        logito();
        Escritorio.add(logito6P);
        alertaStockBajo();
         
    }//GEN-LAST:event_VentasBActionPerformed

   private void logito(){
        Escritorio.add(logito1);
        Escritorio.add(logito2);
        Escritorio.add(logito3);
        Escritorio.add(logito4);
        Escritorio.add(logito5);
       
        
        
        
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JDesktopPane Escritorio;
    private javax.swing.JLabel FondoFrame;
    private javax.swing.JButton HistorialB;
    private javax.swing.JButton ProductosB;
    private javax.swing.JButton ProveedoresB;
    private javax.swing.JButton SolicitarB;
    private javax.swing.JButton VentasB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel logito1;
    private javax.swing.JLabel logito2;
    private javax.swing.JLabel logito3;
    private javax.swing.JLabel logito4;
    private javax.swing.JLabel logito5;
    private javax.swing.JPanel logito6P;
    // End of variables declaration//GEN-END:variables

    
    public static void mensaje(String mensaje){
//        UIManager UI;
//        UI=null;
//        UI.put("OptionPane.background", new Color(13, 139, 223));
//        UI.put("Panel.background", new Color(13, 139, 223));

        Icon alerta;
        alerta = new ImageIcon("src/Imagenes/icons8-alarm-64.png");
        JOptionPane.showConfirmDialog(null, mensaje, "Mensaje Importante", JOptionPane.WARNING_MESSAGE, JOptionPane.INFORMATION_MESSAGE, alerta);
    }
    

    public static void alertaStockBajo(){
        ProductosData prodDS = new ProductosData();
        List<Productos> stockBajo = new ArrayList<>();
        stockBajo = prodDS.listarStockFaltante();
        if(stockBajo.size()>=1){
            mensaje("Uno o más productos están por debajo del stock mínimo.");
        }
    }
 
    
}
