/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import AccesoADatos.ComprasData;
import AccesoADatos.DetalleData;
import AccesoADatos.ProductosData;
import AccesoADatos.ProveedorData;
import Entidades.Productos;
import java.awt.Color;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;

/**
 *
 * @author ariel
 */
public class mainMenu extends javax.swing.JFrame {
  
    private ProductosData prodD;
    private ProveedorData provD;
    private ComprasData compD;
    private DetalleData detaD;
    
    public mainMenu() {
        this.prodD = new ProductosData();
        this.provD = new ProveedorData();
        this.compD = new ComprasData();
        this.detaD = new DetalleData();
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);

        //loggin();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Escritorio = new javax.swing.JDesktopPane();
        logito3 = new javax.swing.JLabel();
        logito2 = new javax.swing.JLabel();
        logito4 = new javax.swing.JLabel();
        logito1 = new javax.swing.JLabel();
        logito5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        ProductosB = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        ProveedoresB = new javax.swing.JButton();
        SolicitarB = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        HistorialB = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        FondoFrame = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 102, 102));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Escritorio.setBackground(new java.awt.Color(0, 102, 102));
        Escritorio.setMaximumSize(new java.awt.Dimension(1010, 610));
        Escritorio.setMinimumSize(new java.awt.Dimension(1010, 610));

        logito3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-laptop-100.png"))); // NOI18N

        logito2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-tv-100.png"))); // NOI18N

        logito4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-air-conditioner-100.png"))); // NOI18N

        logito1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-refrigerator-100.png"))); // NOI18N

        logito5.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        logito5.setForeground(new java.awt.Color(255, 255, 255));
        logito5.setText("Bienvenidos a ComprasLocas");

        Escritorio.setLayer(logito3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Escritorio.setLayer(logito2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Escritorio.setLayer(logito4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Escritorio.setLayer(logito1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Escritorio.setLayer(logito5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout EscritorioLayout = new javax.swing.GroupLayout(Escritorio);
        Escritorio.setLayout(EscritorioLayout);
        EscritorioLayout.setHorizontalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EscritorioLayout.createSequentialGroup()
                .addGap(208, 208, 208)
                .addComponent(logito5, javax.swing.GroupLayout.PREFERRED_SIZE, 627, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(175, Short.MAX_VALUE))
            .addGroup(EscritorioLayout.createSequentialGroup()
                .addGap(262, 262, 262)
                .addComponent(logito1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logito4)
                .addGap(257, 257, 257))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EscritorioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(logito2)
                    .addComponent(logito3))
                .addGap(448, 448, 448))
        );
        EscritorioLayout.setVerticalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EscritorioLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(logito5)
                .addGap(34, 34, 34)
                .addComponent(logito3)
                .addGap(48, 48, 48)
                .addGroup(EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logito1)
                    .addComponent(logito4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(logito2)
                .addGap(51, 51, 51))
        );

        getContentPane().add(Escritorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 1010, 610));
        Escritorio.getAccessibleContext().setAccessibleName("");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-products-64.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        ProductosB.setBackground(new java.awt.Color(204, 204, 255));
        ProductosB.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ProductosB.setForeground(new java.awt.Color(0, 0, 102));
        ProductosB.setText("Productos");
        ProductosB.setBorder(null);
        ProductosB.setMaximumSize(new java.awt.Dimension(100, 100));
        ProductosB.setMinimumSize(new java.awt.Dimension(100, 100));
        ProductosB.setPreferredSize(new java.awt.Dimension(100, 100));
        ProductosB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductosBActionPerformed(evt);
            }
        });
        getContentPane().add(ProductosB, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 120, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-supplier-64.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, -1));

        ProveedoresB.setBackground(new java.awt.Color(204, 204, 255));
        ProveedoresB.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ProveedoresB.setForeground(new java.awt.Color(0, 0, 102));
        ProveedoresB.setText("Gestionar Proveedores");
        ProveedoresB.setBorder(null);
        ProveedoresB.setMaximumSize(new java.awt.Dimension(100, 100));
        ProveedoresB.setMinimumSize(new java.awt.Dimension(100, 100));
        ProveedoresB.setPreferredSize(new java.awt.Dimension(100, 100));
        ProveedoresB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProveedoresBActionPerformed(evt);
            }
        });
        getContentPane().add(ProveedoresB, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 150, 30));

        SolicitarB.setBackground(new java.awt.Color(204, 204, 255));
        SolicitarB.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        SolicitarB.setForeground(new java.awt.Color(0, 0, 102));
        SolicitarB.setText("Solicitar Productos");
        SolicitarB.setBorder(null);
        SolicitarB.setMaximumSize(new java.awt.Dimension(100, 100));
        SolicitarB.setMinimumSize(new java.awt.Dimension(100, 100));
        SolicitarB.setPreferredSize(new java.awt.Dimension(100, 100));
        SolicitarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SolicitarBActionPerformed(evt);
            }
        });
        getContentPane().add(SolicitarB, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 140, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-buy-64.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 70, -1));

        HistorialB.setBackground(new java.awt.Color(204, 204, 255));
        HistorialB.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        HistorialB.setForeground(new java.awt.Color(0, 0, 102));
        HistorialB.setText("Historial de Compras");
        HistorialB.setBorder(null);
        HistorialB.setMaximumSize(new java.awt.Dimension(100, 100));
        HistorialB.setMinimumSize(new java.awt.Dimension(100, 100));
        HistorialB.setPreferredSize(new java.awt.Dimension(100, 100));
        HistorialB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HistorialBActionPerformed(evt);
            }
        });
        getContentPane().add(HistorialB, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, 140, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-list-64.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 470, 70, -1));

        FondoFrame.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoAzulaesDefinicion.png"))); // NOI18N
        getContentPane().add(FondoFrame, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ProductosBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductosBActionPerformed
        Escritorio.removeAll();
        Escritorio.repaint();
        ProductoIF mostrar = new ProductoIF(prodD);
        mostrar.setVisible(true);
        Escritorio.add(mostrar);
        Escritorio.moveToFront(mostrar);
         logito();
    }//GEN-LAST:event_ProductosBActionPerformed

    private void ProveedoresBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProveedoresBActionPerformed
        Escritorio.removeAll();
        Escritorio.repaint();
        AdminProveedoresIF mostrar = new AdminProveedoresIF(provD);
        mostrar.setVisible(true);
        Escritorio.add(mostrar);
        Escritorio.moveToFront(mostrar);
         logito();
    }//GEN-LAST:event_ProveedoresBActionPerformed

    private void SolicitarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SolicitarBActionPerformed
        Escritorio.removeAll();
        Escritorio.repaint();
        SolicitarProductoIF mostrar = new SolicitarProductoIF(compD, prodD, provD, detaD);
        mostrar.setVisible(true);
        Escritorio.add(mostrar);
        Escritorio.moveToFront(mostrar);
         logito();
    }//GEN-LAST:event_SolicitarBActionPerformed

    private void HistorialBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HistorialBActionPerformed
        Escritorio.removeAll();
        Escritorio.repaint();
        HistorialCompraIF mostrar = new HistorialCompraIF(compD, prodD, provD, detaD);
        mostrar.setVisible(true);
        Escritorio.add(mostrar);
        Escritorio.moveToFront(mostrar);
         logito();
    }//GEN-LAST:event_HistorialBActionPerformed

   private void logito(){
        Escritorio.add(logito1);
        Escritorio.add(logito2);
        Escritorio.add(logito3);
        Escritorio.add(logito4);
        Escritorio.add(logito5);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JDesktopPane Escritorio;
    private javax.swing.JLabel FondoFrame;
    private javax.swing.JButton HistorialB;
    private javax.swing.JButton ProductosB;
    private javax.swing.JButton ProveedoresB;
    private javax.swing.JButton SolicitarB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel logito1;
    private javax.swing.JLabel logito2;
    private javax.swing.JLabel logito3;
    private javax.swing.JLabel logito4;
    private javax.swing.JLabel logito5;
    // End of variables declaration//GEN-END:variables

    
    public static void mensaje(String mensaje){
        JOptionPane.showMessageDialog(null, mensaje);
    }

    
}
