/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import AccesoADatos.ProveedorData;
import Entidades.Proveedor;
import static Vistas.mainMenu.Escritorio;
import static Vistas.mainMenu.mensaje;

/**
 *
 * @author feded
 */
public class ModificarProveedorIF extends javax.swing.JInternalFrame {

   private Proveedor proveedor;
   private ProveedorData provD;
    public ModificarProveedorIF(ProveedorData provD, Proveedor proveedor) {
        this.provD = provD;
        this.proveedor = proveedor;
        initComponents();
        RazonST.setText(proveedor.getRazonSocial());
        DomicilioT.setText(proveedor.getDomicilio());
        TelefonoT.setText(proveedor.getTelefono()+"");
        EmailT.setText(proveedor.getEmail());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        RazonST = new javax.swing.JTextField();
        DomicilioT = new javax.swing.JTextField();
        TelefonoT = new javax.swing.JTextField();
        GuardarB = new javax.swing.JButton();
        CancelarB = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        EmailT = new javax.swing.JTextField();
        FondoModiProve = new javax.swing.JLabel();

        setTitle("Modificar Proveedor");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Razon Social:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 48, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Domicilio:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 113, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Telefono:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 202, -1, -1));

        RazonST.setBackground(new java.awt.Color(20, 143, 119));
        RazonST.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        RazonST.setForeground(new java.awt.Color(255, 255, 255));
        RazonST.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(RazonST, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 48, 236, -1));

        DomicilioT.setBackground(new java.awt.Color(20, 143, 119));
        DomicilioT.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        DomicilioT.setForeground(new java.awt.Color(255, 255, 255));
        DomicilioT.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(DomicilioT, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 113, 236, -1));

        TelefonoT.setBackground(new java.awt.Color(20, 143, 119));
        TelefonoT.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        TelefonoT.setForeground(new java.awt.Color(255, 255, 255));
        TelefonoT.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(TelefonoT, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 202, 236, -1));

        GuardarB.setBackground(new java.awt.Color(14, 98, 81));
        GuardarB.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        GuardarB.setForeground(new java.awt.Color(255, 255, 255));
        GuardarB.setText("Guardar");
        GuardarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarBActionPerformed(evt);
            }
        });
        getContentPane().add(GuardarB, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 190, -1));

        CancelarB.setBackground(new java.awt.Color(14, 98, 81));
        CancelarB.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        CancelarB.setForeground(new java.awt.Color(255, 255, 255));
        CancelarB.setText("Cancelar");
        CancelarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarBActionPerformed(evt);
            }
        });
        getContentPane().add(CancelarB, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 350, 188, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Email:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 280, -1, -1));

        EmailT.setBackground(new java.awt.Color(20, 143, 119));
        EmailT.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        EmailT.setForeground(new java.awt.Color(255, 255, 255));
        EmailT.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(EmailT, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 280, 236, -1));

        FondoModiProve.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/verdeAzuladoPN.png"))); // NOI18N
        getContentPane().add(FondoModiProve, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 440, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GuardarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarBActionPerformed
       try{
        int id = proveedor.getIdProveedor();
        String razon = RazonST.getText();
        String domicilio = DomicilioT.getText();
        String tel = TelefonoT.getText();
        String correo = EmailT.getText();
        Boolean estado = proveedor.isEstado();
        
        Proveedor modificar = new Proveedor (id, razon, domicilio, correo, tel, estado);
           System.out.println(modificar);
        provD.modificarProveedor(modificar);
        
        Escritorio.removeAll();
        Escritorio.repaint();
        AdminProveedoresIF apif = new AdminProveedoresIF(provD);
        apif.setVisible(true);
        Escritorio.add(apif);
        Escritorio.moveToFront(apif);
        }catch (NullPointerException ex) {
            mensaje("No pueden quedar campos vacíos.");
            System.out.println(ex.getMessage());
        } catch (NumberFormatException ex) {
            mensaje("Debe ingresar un valor válido.");
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_GuardarBActionPerformed

    private void CancelarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarBActionPerformed
            Escritorio.removeAll();
            Escritorio.repaint();
            AdminProveedoresIF apif = new AdminProveedoresIF(provD);
            apif.setVisible(true);
            Escritorio.add(apif);
            Escritorio.moveToFront(apif);
    }//GEN-LAST:event_CancelarBActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelarB;
    private javax.swing.JTextField DomicilioT;
    private javax.swing.JTextField EmailT;
    private javax.swing.JLabel FondoModiProve;
    private javax.swing.JButton GuardarB;
    private javax.swing.JTextField RazonST;
    private javax.swing.JTextField TelefonoT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
