/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import AccesoADatos.ProductosData;
import Entidades.Productos;
import static Vistas.mainMenu.Escritorio;
import static Vistas.mainMenu.mensaje;

/**
 *
 * @author ariel
 */
public class ModificarProductoIF extends javax.swing.JInternalFrame {

    /**
     * Creates new form ModificarProductoIF
     */
    private Productos producto;
    private ProductosData prodD;
    public ModificarProductoIF(ProductosData prodD, Productos producto) {
        initComponents();
        this.prodD=prodD;
        this.producto=producto;
        NombreT.setText(producto.getNombre());
        DesT.setText(producto.getDescripcion());
        RubroCB.setSelectedItem(producto.getRubro());
        PrecioAT.setText(producto.getPrecioActual()+"");
        stockT.setText(producto.getStock()+"");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        NombreT = new javax.swing.JTextField();
        DesT = new javax.swing.JTextField();
        PrecioAT = new javax.swing.JTextField();
        RubroCB = new javax.swing.JComboBox<>();
        ModificarB = new javax.swing.JButton();
        CancelarB = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        stockT = new javax.swing.JTextField();
        FondoModiProd = new javax.swing.JLabel();

        setTitle("Modificar Productos");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Nombre:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 34, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Descripcion:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 84, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Rubro:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("PrecioActual:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        NombreT.setBackground(new java.awt.Color(20, 143, 119));
        NombreT.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        NombreT.setForeground(new java.awt.Color(255, 255, 255));
        NombreT.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(NombreT, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 230, 20));

        DesT.setBackground(new java.awt.Color(20, 143, 119));
        DesT.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        DesT.setForeground(new java.awt.Color(255, 255, 255));
        DesT.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(DesT, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 230, 20));

        PrecioAT.setBackground(new java.awt.Color(20, 143, 119));
        PrecioAT.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        PrecioAT.setForeground(new java.awt.Color(255, 255, 255));
        PrecioAT.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(PrecioAT, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 230, 20));

        RubroCB.setBackground(new java.awt.Color(20, 143, 119));
        RubroCB.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        RubroCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hogar", "Cocina", "Pequeños Electrodomésticos" }));
        RubroCB.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(RubroCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 230, -1));

        ModificarB.setBackground(new java.awt.Color(14, 98, 81));
        ModificarB.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        ModificarB.setForeground(new java.awt.Color(255, 255, 255));
        ModificarB.setText("Modificar");
        ModificarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarBActionPerformed(evt);
            }
        });
        getContentPane().add(ModificarB, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 188, -1));

        CancelarB.setBackground(new java.awt.Color(14, 98, 81));
        CancelarB.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        CancelarB.setForeground(new java.awt.Color(255, 255, 255));
        CancelarB.setText("Cancelar");
        CancelarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarBActionPerformed(evt);
            }
        });
        getContentPane().add(CancelarB, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 350, 188, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Stock:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        stockT.setBackground(new java.awt.Color(20, 143, 119));
        stockT.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        stockT.setForeground(new java.awt.Color(255, 255, 255));
        stockT.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(stockT, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 230, -1));

        FondoModiProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/verdeAzuladoPN.png"))); // NOI18N
        getContentPane().add(FondoModiProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 440, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ModificarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarBActionPerformed
       try{
           
           int id = producto.getIdProducto();
           String nom = NombreT.getText();
           String des = DesT.getText();
           String rub =(String) RubroCB.getSelectedItem();
           double precio = Double.parseDouble(PrecioAT.getText());
           Boolean estado = producto.isEstado();
           int stock = Integer.parseInt(stockT.getText());
           
           Productos modificar = new Productos (id, nom, des, rub, precio,stock, estado);
           prodD.modificarProducto(modificar);
           
            Escritorio.removeAll();
            Escritorio.repaint();
            ProductoIF pif = new ProductoIF(prodD);
            pif.setVisible(true);
            Escritorio.add(pif);
            Escritorio.moveToFront(pif);
            
            
      }catch (NullPointerException ex) {
            mensaje("No pueden quedar campos vacíos.");
            System.out.println(ex.getMessage());
        } catch (NumberFormatException ex) {
            mensaje("Debe ingresar un valor válido.");
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_ModificarBActionPerformed

    private void CancelarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarBActionPerformed
            Escritorio.removeAll();
            Escritorio.repaint();
            ProductoIF pif = new ProductoIF(prodD);
            pif.setVisible(true);
            Escritorio.add(pif);
            Escritorio.moveToFront(pif);
    }//GEN-LAST:event_CancelarBActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelarB;
    private javax.swing.JTextField DesT;
    private javax.swing.JLabel FondoModiProd;
    private javax.swing.JButton ModificarB;
    private javax.swing.JTextField NombreT;
    private javax.swing.JTextField PrecioAT;
    private javax.swing.JComboBox<String> RubroCB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField stockT;
    // End of variables declaration//GEN-END:variables
}
