/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

/**
 *
 * @author ariel
 */
public class ProductoIF extends javax.swing.JInternalFrame {

    /**
     * Creates new form AgregarProductoIF
     */
    public ProductoIF() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        AgregarB = new javax.swing.JButton();
        ModificarB = new javax.swing.JButton();
        NombreT = new javax.swing.JTextField();
        DescripcionT = new javax.swing.JTextField();
        RubroT = new javax.swing.JTextField();
        PrecioT = new javax.swing.JTextField();
        StockT = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListaProducto = new javax.swing.JTable();
        grisDer = new javax.swing.JLabel();
        grisIzq = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Agregar Productos");
        setMaximumSize(new java.awt.Dimension(1008, 605));
        setMinimumSize(new java.awt.Dimension(1008, 605));
        setPreferredSize(new java.awt.Dimension(1008, 605));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("Agregar Productos");
        jLabel1.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 270, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setText("Listado de Productos");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 40, -1, -1));

        jLabel3.setText("Descripcion");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, 20));

        jLabel4.setText("Nombre");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, 20));

        jLabel5.setText("Rubro");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, 20));

        jLabel6.setText("Precio Actual");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, -1, 20));

        jLabel7.setText("Stock");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, -1, 20));

        AgregarB.setText("Agregar");
        getContentPane().add(AgregarB, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, 450, -1));

        ModificarB.setText("Modificar");
        getContentPane().add(ModificarB, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 490, 450, -1));
        getContentPane().add(NombreT, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 320, -1));
        getContentPane().add(DescripcionT, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 320, -1));
        getContentPane().add(RubroT, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 320, -1));
        getContentPane().add(PrecioT, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, 320, -1));
        getContentPane().add(StockT, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 390, 320, -1));

        ListaProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(ListaProducto);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(523, 100, 460, 360));

        grisDer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/gris.png"))); // NOI18N
        grisDer.setMaximumSize(new java.awt.Dimension(500, 250));
        grisDer.setMinimumSize(new java.awt.Dimension(500, 250));
        grisDer.setPreferredSize(new java.awt.Dimension(500, 250));
        getContentPane().add(grisDer, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 10, 480, 560));

        grisIzq.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/gris.png"))); // NOI18N
        getContentPane().add(grisIzq, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 480, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarB;
    private javax.swing.JTextField DescripcionT;
    private javax.swing.JTable ListaProducto;
    private javax.swing.JButton ModificarB;
    private javax.swing.JTextField NombreT;
    private javax.swing.JTextField PrecioT;
    private javax.swing.JTextField RubroT;
    private javax.swing.JTextField StockT;
    private javax.swing.JLabel grisDer;
    private javax.swing.JLabel grisIzq;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
