/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;
import javax.swing.ImageIcon;
import AccesoADatos.ProductosData;
import Entidades.Productos;
import static Vistas.mainMenu.Escritorio;
import static Vistas.mainMenu.mensaje;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;


public class ProductoIF extends javax.swing.JInternalFrame {

    private ProductosData prodD;
    private DefaultTableModel modelo = new DefaultTableModel(){
        public boolean isCellEditable(int f, int c) {
            return false;
        }
    };
    List<Productos> lista = new ArrayList<>();
    public ProductoIF(ProductosData prodD) {
        this.prodD = prodD;
        initComponents();
        armarCabecera();
        ActivosRB.setSelected(true);
        listar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Grupo = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        EliminarB = new javax.swing.JButton();
        AgregarB = new javax.swing.JButton();
        RubroCB = new javax.swing.JComboBox<>();
        ModificarB = new javax.swing.JButton();
        NombreT = new javax.swing.JTextField();
        DescripcionT = new javax.swing.JTextField();
        PrecioT = new javax.swing.JTextField();
        StockT = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListaProducto = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        InactivosRB = new javax.swing.JRadioButton();
        ActivosRB = new javax.swing.JRadioButton();
        FondoDer = new javax.swing.JLabel();
        FondoIzq = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 153, 255));
        setClosable(true);
        setTitle("Agregar Productos");
        setMaximumSize(new java.awt.Dimension(1008, 605));
        setMinimumSize(new java.awt.Dimension(1008, 605));
        setPreferredSize(new java.awt.Dimension(1010, 610));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 51));
        jLabel1.setText("Agregar Productos");
        jLabel1.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 210, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 51));
        jLabel2.setText("Listado de Productos");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 40, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Descripcion:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, 20));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Nombre:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, 20));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Rubro:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, 20));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Precio Actual:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, -1, 20));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("Stock:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, -1, 20));

        EliminarB.setBackground(new java.awt.Color(14, 98, 81));
        EliminarB.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        EliminarB.setForeground(new java.awt.Color(255, 255, 255));
        EliminarB.setText("Modificar Estado");
        EliminarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarBActionPerformed(evt);
            }
        });
        getContentPane().add(EliminarB, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 490, 220, -1));

        AgregarB.setBackground(new java.awt.Color(14, 98, 81));
        AgregarB.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        AgregarB.setForeground(new java.awt.Color(255, 255, 255));
        AgregarB.setText("Agregar Producto");
        AgregarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarBActionPerformed(evt);
            }
        });
        getContentPane().add(AgregarB, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, 450, -1));

        RubroCB.setBackground(new java.awt.Color(20, 143, 119));
        RubroCB.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        RubroCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hogar", "Cocina", "Pequeños Electrodomésticos" }));
        RubroCB.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(RubroCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 320, 20));

        ModificarB.setBackground(new java.awt.Color(14, 98, 81));
        ModificarB.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        ModificarB.setForeground(new java.awt.Color(255, 255, 255));
        ModificarB.setText("Modificar Producto");
        ModificarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarBActionPerformed(evt);
            }
        });
        getContentPane().add(ModificarB, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 490, 230, -1));

        NombreT.setBackground(new java.awt.Color(20, 143, 119));
        NombreT.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        NombreT.setForeground(new java.awt.Color(255, 255, 255));
        NombreT.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        NombreT.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(NombreT, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 114, 320, 20));

        DescripcionT.setBackground(new java.awt.Color(20, 143, 119));
        DescripcionT.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        DescripcionT.setForeground(new java.awt.Color(255, 255, 255));
        DescripcionT.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        DescripcionT.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(DescripcionT, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 320, 20));

        PrecioT.setBackground(new java.awt.Color(20, 143, 119));
        PrecioT.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        PrecioT.setForeground(new java.awt.Color(255, 255, 255));
        PrecioT.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        PrecioT.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(PrecioT, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, 320, 20));

        StockT.setBackground(new java.awt.Color(20, 143, 119));
        StockT.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        StockT.setForeground(new java.awt.Color(255, 255, 255));
        StockT.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        StockT.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(StockT, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 390, 320, 20));

        ListaProducto.setBackground(new java.awt.Color(20, 143, 119));
        ListaProducto.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        ListaProducto.setForeground(new java.awt.Color(255, 255, 255));
        ListaProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Precio", "Stock"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ListaProducto.setGridColor(new java.awt.Color(204, 204, 204));
        ListaProducto.setSelectionBackground(new java.awt.Color(153, 153, 153));
        jScrollPane1.setViewportView(ListaProducto);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(523, 100, 460, 360));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setText("Inactivos");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 530, -1, 30));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel10.setText("Mostrar:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 530, -1, 30));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel11.setText("Activos");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 530, -1, 30));

        Grupo.add(InactivosRB);
        InactivosRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InactivosRBActionPerformed(evt);
            }
        });
        getContentPane().add(InactivosRB, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 530, 20, 30));

        ActivosRB.setBackground(new java.awt.Color(255, 255, 255));
        Grupo.add(ActivosRB);
        ActivosRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActivosRBActionPerformed(evt);
            }
        });
        getContentPane().add(ActivosRB, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 530, 20, 30));

        FondoDer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/verdeAzuladoPN.png"))); // NOI18N
        FondoDer.setMaximumSize(new java.awt.Dimension(500, 250));
        FondoDer.setMinimumSize(new java.awt.Dimension(500, 250));
        FondoDer.setPreferredSize(new java.awt.Dimension(500, 250));
        getContentPane().add(FondoDer, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, 490, 580));

        FondoIzq.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/verdeAzuladoPN.png"))); // NOI18N
        getContentPane().add(FondoIzq, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AgregarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarBActionPerformed
        // Boton para agregar un producto
        try{
            String nombre = NombreT.getText();
            String desc = DescripcionT.getText();
            String rubro = (String) RubroCB.getSelectedItem();
            Double precioA = Double.parseDouble(PrecioT.getText());
            int stock = Integer.parseInt(StockT.getText());
            Productos prod = new Productos(nombre, desc, rubro, precioA, stock, true);
            
            prodD.agregarProducto(prod);
            
            NombreT.setText("");
            DescripcionT.setText("");
            PrecioT.setText("");
            StockT.setText("");
            listar();
        }catch(NumberFormatException ex){
            mensaje("Hay campos vacíos o valores mal ingresados, revisar el formulario.");
            System.out.println(ex.getMessage());
        }catch(NullPointerException ex){
            mensaje("Hay campos vacíos o valores mal ingresados, revisar el formulario.");
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_AgregarBActionPerformed

    private void EliminarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarBActionPerformed
        // Boton para eliminar el producto
        try{    
            int selec = ListaProducto.getSelectedRow();
            int id = (int) ListaProducto.getValueAt(selec, 0);

            if(ActivosRB.isSelected()){
                prodD.altaBajaProducto(id, 0);
            }else if(InactivosRB.isSelected()){
                prodD.altaBajaProducto(id, 1);
            }
            listar();
        }catch(ArrayIndexOutOfBoundsException ex){
            mensaje("Debe seleccionar un producto de la tabla.");
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_EliminarBActionPerformed

    private void ActivosRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActivosRBActionPerformed
        // Listar activos
        listar();
    }//GEN-LAST:event_ActivosRBActionPerformed

    private void InactivosRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InactivosRBActionPerformed
        // Listar inactivos
        listar();
    }//GEN-LAST:event_InactivosRBActionPerformed

    private void ModificarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarBActionPerformed
        try{
            int fila = ListaProducto.getSelectedRow();
            int id = (int) ListaProducto.getValueAt(fila,0);
            Productos modificar = new Productos();
            
            modificar = lista.get(fila);
            ModificarProductoIF mostrar = new ModificarProductoIF(prodD,modificar);
            mostrar.setVisible(true);
            Escritorio.add(mostrar);
            Escritorio.moveToFront(mostrar);
           
            
        }catch(ArrayIndexOutOfBoundsException ex){
            mensaje("Debe seleccionar un producto de la tabla.");
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_ModificarBActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton ActivosRB;
    private javax.swing.JButton AgregarB;
    private javax.swing.JTextField DescripcionT;
    private javax.swing.JButton EliminarB;
    private javax.swing.JLabel FondoDer;
    private javax.swing.JLabel FondoIzq;
    private javax.swing.ButtonGroup Grupo;
    private javax.swing.JRadioButton InactivosRB;
    private javax.swing.JTable ListaProducto;
    private javax.swing.JButton ModificarB;
    private javax.swing.JTextField NombreT;
    private javax.swing.JTextField PrecioT;
    private javax.swing.JComboBox<String> RubroCB;
    private javax.swing.JTextField StockT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables


    public void listar(){
        borrarFilas();
        if (ActivosRB.isSelected()) {
            lista = prodD.listarProductos(1);
        } else if(InactivosRB.isSelected()){
            lista = prodD.listarProductos(0);
        }
        
       for (Productos productos : lista) {
            modelo.addRow(new Object[]{productos.getIdProducto(), productos.getNombre(),productos.getPrecioActual(), productos.getStock()});
        }
    }
    
    public void borrarFilas(){
        int f = ListaProducto.getRowCount() - 1;
        for (; f >= 0; f--) {
            modelo.removeRow(f);
        }
    }
    
    public void armarCabecera(){
        modelo.addColumn("ID");
        modelo.addColumn("Nombre");
        modelo.addColumn("Precio");
        modelo.addColumn("Stock");
        ListaProducto.setModel(modelo);
    }
}
