/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import AccesoADatos.ComprasData;
import AccesoADatos.ProductosData;
import AccesoADatos.ProveedorData;
import Entidades.Compras;
import Entidades.Productos;
import Entidades.Proveedor;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Servidor
 */
public class ProveedoresIF extends javax.swing.JInternalFrame {

    private ProductosData prodD;
    private ProveedorData provD;
    private ComprasData compD;
 private DefaultTableModel modelo1 = new DefaultTableModel();
 private DefaultTableModel modelo2 = new DefaultTableModel();
 List<Proveedor> listaProv = new ArrayList<>();
 List<Productos> listaProd = new ArrayList<>();
 List<Compras> listaComp = new ArrayList<>();
 
    public ProveedoresIF(ProveedorData provD, ProductosData prodD, ComprasData compD) {
        this.prodD = prodD;
        this.provD = provD;
        this.compD = compD;
        initComponents();
        armarCabeceraPro();
        armarCabeceraCompra();
        llenarComboBox();
//        setSize(450, 500);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ProveedoresJCB = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaCompra = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaPro = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();

        setClosable(true);

        ProveedoresJCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProveedoresJCBActionPerformed(evt);
            }
        });

        jLabel1.setText("Compras por Proveedores");

        TablaCompra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TablaCompra);

        jLabel2.setText("Lista de Productos por Proveedor");

        TablaPro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(TablaPro);

        jLabel3.setText("Seleccione un Proveedor");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(106, 106, 106))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ProveedoresJCB, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(202, 202, 202))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ProveedoresJCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ProveedoresJCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProveedoresJCBActionPerformed
        // Seleccion en el comboBox
        listaProd = prodD.listarProductos(1);
        for (Productos prod : listaProd) {
            modelo1.addRow(new Object[]{prod.getNombre(), prod.getRubro(), prod.getPrecioActual(), prod.getStock()});
        }
        
        Proveedor prov = (Proveedor) ProveedoresJCB.getSelectedItem();
        int id = prov.getIdProveedor();
        listaComp = compD.comprasPorProveedor(id);
        for (Compras compra : listaComp) {
            modelo2.addRow(new Object[]{compra.getIdCompra(), compra.getFecha(), compra.getPrecioTotal()});
        }
    }//GEN-LAST:event_ProveedoresJCBActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<Proveedor> ProveedoresJCB;
    private javax.swing.JTable TablaCompra;
    private javax.swing.JTable TablaPro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
    public void armarCabeceraPro(){
        modelo1.addColumn("Nombre");
        modelo1.addColumn("Rubro");
        modelo1.addColumn("Precio");
        modelo1.addColumn("Cantidad");
        TablaPro.setModel(modelo1);
    }
    public void armarCabeceraCompra(){
        modelo2.addColumn("ID");
        modelo2.addColumn("Fecha");
        modelo2.addColumn("Precio Total de la Compra");
        TablaCompra.setModel(modelo2);
    }
    
    public void llenarComboBox(){
        
        listaProv = provD.listarProveedores(1);
        
        for (Proveedor proveedor : listaProv) {
            ProveedoresJCB.addItem(proveedor);
        }
        
    }
}
